#!/usr/bin/env python3

import configparser

from jira import JIRA

# Read the configuration file.
with open('~/.jisues') as conf_file:
    lines = chain(('[top]',), lines)
    config = configparser.ConfigParser()
    config.read_file(lines)

print(config.sections())

server = config['jissues']['server']
user = config['jissues']['user']
password = config['jissues']['password']

options = {'server': server}
jira = JIRA(options, basic_auth=(user, password))

size = 100
initial = 0
while True:
    start = initial*size
    issues = jira.search_issues('project=PSE and issuetype=Story and sprint in openSprints() ORDER BY key ASC',  start, size)
    if len(issues) == 0:
        break
    initial += 1
    for issue in issues:
        print(issue,': ', issue.fields.summary, sep="")
